name: Hello Self Hosted

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Hello
        run: |
          echo "Hello from my self-hosted runner!"
          echo "Current user: $(whoami)"
          echo "Hostname: $(hostname)"
          echo "Operating System:"
          uname -a
          echo "Current Directory:"
          pwd
          echo "Date:"
          date
